name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup NodeJS 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run linter
        run: yarn run lint
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Cypress Test
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          working-directory: frontend
          build: yarn run build
          start: yarn run start
